"""Add shipping and offer columns to Post

Revision ID: f508f0975d6a
Revises: bedcf4178b26
Create Date: 2024-07-08 11:37:20.177125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f508f0975d6a'
down_revision = 'bedcf4178b26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('offer', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('offer')
        batch_op.drop_column('shipping')

    # ### end Alembic commands ###
